name: CI - Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**' # Only trigger if application code changes

env:
  ACR_NAME: 'acrecommerce7eeaed12'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name ${{ env.ACR_NAME }}

    - name: Build and Push Microservices
      run: |
        for app in health auth catalog ordering payment; do
          echo "Building and pushing $app..."
          docker build --build-arg APP_NAME=$app -t ${{ env.ACR_NAME }}.azurecr.io/$app:latest ./src
          docker push ${{ env.ACR_NAME }}.azurecr.io/$app:latest
        done