
name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: 'acrecommerce7eeaed12'
  AKS_CLUSTER_NAME: 'aks-ecommerce-public'
  RESOURCE_GROUP: 'rg-ecommerce-prod'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Updated to v4
    - name: Checkout Code
      uses: actions/checkout@v4

    # Updated to v2
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    - name: Build and Push Microservices
      run: |
        for app in health auth catalog ordering payment; do
          echo "Building and pushing $app..."
          docker build --build-arg APP_NAME=$app -t ${{ env.ACR_NAME }}.azurecr.io/$app:latest ./src
          docker push ${{ env.ACR_NAME }}.azurecr.io/$app:latest
        done
    # 1. ADD THIS NEW STEP
    - name: Set up kubelogin
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.1.1'
        kubelogin-release-tag: 'v0.1.1'
    - name: Set AKS Context
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    - name: Deploy Manifest to AKS
      run: |
        kubectl apply -f apps.yaml
        
        kubectl rollout restart deployment health-deployment auth-deployment catalog-deployment ordering-deployment payment-deployment